name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Manually check out your repo
      - name: Checkout code
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE

      # 2. Install Node.js 17 via NodeSource (ubuntu-latest comes with curl and sudo)
      - name: Install Node.js 17
        run: |
          curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
          sudo apt-get update
          sudo apt-get install -y nodejs

      # 3. Install your npm deps and run tests
      - name: Install deps & test
        run: |
          cd $GITHUB_WORKSPACE
          npm ci
          npm test

      # 4. Log in to your Docker registry
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} \
            --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # 5. Build & push your image with two tags
      - name: Build & push Docker image
        run: |
          cd $GITHUB_WORKSPACE
          IMAGE="${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/frontend"
          docker build -t "$IMAGE:latest" .
          docker tag "$IMAGE:latest" "$IMAGE:${{ github.sha }}"
          docker push "$IMAGE:latest"
          docker push "$IMAGE:${{ github.sha }}"
