  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

-     - name: Setup SSH key and agent
-       run: |
-         mkdir -p ~/.ssh
-         echo "${{ secrets.SWARM_SSH_KEY }}" > ~/.ssh/id_rsa
-         chmod 600 ~/.ssh/id_rsa
-
-         # convert key to PEM for compatibility
-         ssh-keygen -p -N "" -m PEM -f ~/.ssh/id_rsa
-
-         eval "$(ssh-agent -s)"
-         ssh-add ~/.ssh/id_rsa
+     - name: Setup SSH key and agent
+       run: |
+         mkdir -p ~/.ssh
+         # write the key exactly as stored (preserves newlines)
+         cat << 'EOK' > ~/.ssh/id_rsa
+${{ secrets.SWARM_SSH_KEY }}
+EOK
+         chmod 600 ~/.ssh/id_rsa
+
+         # start ssh-agent and add your key
+         eval "$(ssh-agent -s)"
+         ssh-add ~/.ssh/id_rsa

      - name: Deploy to Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ secrets.SWARM_SSH_PORT }} \
              ${{ secrets.SWARM_USER }}@${{ secrets.SWARM_HOST }} << 'EOF'
            echo "${{ secrets.DOCKER_PASSWORD }}" \
              | docker login ${{ secrets.DOCKER_REGISTRY }} \
                  --username ${{ secrets.DOCKER_USERNAME }} \
                  --password-stdin

            docker stack deploy \
              -c /home/${{ secrets.SWARM_USER }}/docker-compose.yml \
              frontend-stack \
              --with-registry-auth
          EOF
