name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout code
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE

      # 2. Install nvm & Node.js 17 using the runner's temp directory
      - name: Install nvm and Node.js 17
        run: |
          # Set NVM_DIR inside the runner's temp folder
          export NVM_DIR="$RUNNER_TEMP/.nvm"
          mkdir -p "$NVM_DIR"

          # Install nvm
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

          # Load nvm and install Node 17
          source "$NVM_DIR/nvm.sh"
          nvm install 17
          nvm use 17

          # Verify
          echo "Node version: $(node -v)"
          echo "npm version:  $(npm -v)"

      # 3. Install dependencies & run tests
      - name: Install deps & test
        run: |
          cd $GITHUB_WORKSPACE
          npm ci
          npm test

      # 4. Docker login
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login ${{ secrets.DOCKER_REGISTRY }} \
              --username ${{ secrets.DOCKER_USERNAME }} \
              --password-stdin

      # 5. Build & push Docker image
      - name: Build & push Docker image
        run: |
          cd $GITHUB_WORKSPACE
          IMAGE="${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/frontend"
          docker build -t "$IMAGE:latest" .
          docker tag "$IMAGE:latest" "$IMAGE:${{ github.sha }}"
          docker push "$IMAGE:latest"
          docker push "$IMAGE:${{ github.sha }}"
