name: CI

# trigger on any push to main (and PRs targeting main)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Grab your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js 17
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17'

      # 3. Install dependencies & run your tests
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

      # 4. Log in to your Docker registry
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build your image (uses your Dockerfile) and push it
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/frontend:latest
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
